#!/bin/bash

parse_ini() {
    INIFILE=$1
    SECTION=$2
    ITEM=$3

    awk -v section="$SECTION" -v item="$ITEM" '
        /^\[/ {
            if ($0 == "[" section "]") {
                in_section = 1
            } else if (in_section) {
                exit
            }
            next
        }
        in_section && $0 ~ "^[[:space:]]*" item "[[:space:]]*=" {
            sub(/^[^=]*=[[:space:]]*/, "")
            gsub(/[[:space:]]/, "")
            print
            exit
        }
    ' "$INIFILE"
}

# for SECTION in "lenovo"; do
for SECTION in "${3}"; do
    BUILD_LIB=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_LIB)
    BUILD_DEB=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_DEB)
    BUILD_RPM=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_RPM)
    BUILD_HELPER=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_HELPER)
    BUILD_DOWN_TOOL=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_DOWN_TOOL)
    BUILD_FLASH=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_FLASH)
    BUILD_CONFIG=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_CONFIG)
    BUILD_MA=$(parse_ini ${1}/${2}_config "$SECTION" BUILD_MA)
done
    cat <<EOF > "${1}/build/${2}_${3}_config.cmake"
set(PROJECT_BUILD "${2}")
set(OEM_BUILD "${3}")
set(BUILD_LIB "${BUILD_LIB}")
set(BUILD_DEB "${BUILD_DEB}")
set(BUILD_RPM "${BUILD_RPM}")
set(BUILD_HELPER "${BUILD_HELPER}")
set(BUILD_DOWN_TOOL "${BUILD_DOWN_TOOL}")
set(BUILD_FLASH "${BUILD_FLASH}")
set(BUILD_CONFIG "${BUILD_CONFIG}")
set(BUILD_MA "${BUILD_MA}")
EOF
