#! /bin/bash

basedir=`cd \`dirname $0\`; pwd`
BUILD_DIR=${basedir}/build
APP_DIR="${BUILD_DIR}/application"
CONFIG_SERVICE_APP_DIR="${APP_DIR}/rolling_config_service"
CONFIG_SERVICE_APP_PATH="${APP_DIR}/rolling_config_service/rolling_config*"
FLASH_SERVICE_APP_PATH="${APP_DIR}/rolling_flash_service/rolling_flash*"
FLASH_SERVICE_APP_DIR="${APP_DIR}/rolling_flash_service"
HELPER_SERVICE_APP_PATH="${APP_DIR}/rolling_helper_service/"


DEB_SOFT_DIRS="${BUILD_DIR}/release/dpkg"
DEB_SOFT_DIR="${DEB_SOFT_DIRS}/opt/rolling"
DEB_CONFIG_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_config_service"
DEB_FLASH_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_flash_service"
DEB_HELPER_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_helper_service"

BUILD_HELPER=$(grep -o 'set(BUILD_HELPER "[^"]*"' ${BUILD_DIR}/*_config.cmake | awk -F'"' '{print $2}')
BUILD_DOWN_TOOL=$(grep -o 'set(BUILD_DOWN_TOOL "[^"]*"' ${BUILD_DIR}/*_config.cmake | awk -F'"' '{print $2}')
BUILD_FLASH=$(grep -o 'set(BUILD_FLASH "[^"]*"' ${BUILD_DIR}/*_config.cmake | awk -F'"' '{print $2}')
BUILD_CONFIG=$(grep -o 'set(BUILD_CONFIG "[^"]*"' ${BUILD_DIR}/*_config.cmake | awk -F'"' '{print $2}')
OEM_BUILD=$(grep -o 'set(OEM_BUILD "[^"]*"' ${BUILD_DIR}/*_config.cmake | awk -F'"' '{print $2}')
echo "OEM_BUILD: ${OEM_BUILD}"

echo "build helper package ${BUILD_HELPER}"
echo "build down tool package ${BUILD_DOWN_TOOL}"
echo "build flash package ${BUILD_FLASH}"
echo "build config package ${BUILD_CONFIG}"

function operation_menu_select()
{
    echo -e "\033[32m=================================================== \033[0m"
    echo -e "\033[35m operation select:\033[0m"
    for list in ${BUILD_LIST[@]}; do
        echo -e "\033[32m    --------------------------------- \033[0m"
        COUNT=$(($COUNT+1)); echo -e "\033[35m    $COUNT.$list \033[0m"
    done
}

# 修改copy_file_to_deb_directory函数
function copy_file_to_deb_directory()
{
    # copy configservice file
    if [ "$(ls -A $DEB_CONFIG_SERVICE_DIR)" ]; then
        rm -r ${DEB_CONFIG_SERVICE_DIR}/*
    fi
    if [ "$(ls -A $DEB_FLASH_SERVICE_DIR)" ]; then
        rm -r ${DEB_FLASH_SERVICE_DIR}/*
    fi

    if [ "yes" == "${BUILD_CONFIG}" ]; then
        cp -raf ${CONFIG_SERVICE_APP_DIR}/*.ini ${DEB_CONFIG_SERVICE_DIR}
        # 使用cp -f命令，不存在时不会报错
        cp -fraf ${CONFIG_SERVICE_APP_PATH} ${DEB_CONFIG_SERVICE_DIR} 2>/dev/null || true
    fi

    if [ "yes" == "${BUILD_FLASH}" ]; then
        DEB_FLASH_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_flash_service"
        cp -raf ${FLASH_SERVICE_APP_DIR}/*.ini ${DEB_FLASH_SERVICE_DIR}
        # 使用cp -f命令，不存在时不会报错
        cp -fraf ${FLASH_SERVICE_APP_PATH} ${DEB_FLASH_SERVICE_DIR} 2>/dev/null || true
    fi

    if [ "yes" == "${BUILD_HELPER}" ]; then
        if [ "$(ls -A $DEB_HELPER_SERVICE_DIR)" ]; then
            path=`pwd`
            cd $DEB_HELPER_SERVICE_DIR
            ls | grep -v  rolling_helper_tools  | awk  '{system("rm -rf "$1)}'
            cd $path
        fi
        # 使用cp -f命令，不存在时不会报错
        cp -fraf ${HELPER_SERVICE_APP_PATH}/*rolling_helper ${DEB_HELPER_SERVICE_DIR} 2>/dev/null || true
        # 确保实际二进制文件被重命名为rolling_helper
        for bin_file in ${DEB_HELPER_SERVICE_DIR}/*rolling_helper; do
            if [ -f "$bin_file" ] && [ "$bin_file" != "${DEB_HELPER_SERVICE_DIR}/rolling_helper" ]; then
                mv "$bin_file" "${DEB_HELPER_SERVICE_DIR}/rolling_helper"
                break
            fi
        done
    fi
}

function create_helper_conf()
{
    echo "<!DOCTYPE busconfig PUBLIC
 \"-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN\"
 \"http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd\">
<busconfig>
  <!-- This config allows anyone to control mcdm -->

  <policy context=\"default\">
    <allow send_destination=\"com.rolling.helper\"/>
  </policy>

  <policy user=\"root\">
    <allow own=\"com.rolling.helper\"/>
  </policy>
</busconfig>" > $1/com.rolling.helper.conf
    chmod 644 $1/com.rolling.helper.conf
}

function create_config_service()
{
    echo "[Unit]
Description=Firmware Config Service
After=ModemManager.service rolling_helper.service

[Service]
EnvironmentFile=/lib/systemd/system/rolling_config.d/env.conf
ExecStart=/opt/rolling/rolling_config_service/rolling_config
ExecReload=/bin/kill -HUP \$MAINPID
Restart=on-abort
Type=simple
User=root

[Install]
Alias=rolling_config.service
WantedBy=multi-user.target" > $1/rolling_config.service
    chmod 644 $1/rolling_config.service
}

function create_flash_service()
{
    echo "[Unit]
Description=Firmware Flash Service
After=ModemManager.service rolling_helper.service
[Service]
EnvironmentFile=/lib/systemd/system/rolling_flash.d/env.conf
ExecStart=/opt/rolling/rolling_flash_service/rolling_flash
ExecReload=/bin/kill -HUP \$MAINPID
Restart=on-abort
Type=simple
User=root

[Install]
Alias=rolling_flash.service
WantedBy=multi-user.target" > $1/rolling_flash.service
    chmod 644 $1/rolling_flash.service

}

function create_helper_service()
{
    echo "[Unit]
Description=Firmware Helper Service
After=ModemManager.service

[Service]
EnvironmentFile=/lib/systemd/system/rolling_helper.d/env.conf
ExecStart=/opt/rolling/rolling_helper_service/rolling_helper
ExecReload=/bin/kill -HUP \$MAINPID
Restart=on-abort
Type=simple
User=root

[Install]
Alias=rolling_helper.service
WantedBy=multi-user.target" > $1/rolling_helper.service
    chmod 644 $1/rolling_helper.service

}

function create_config_d()
{
    echo "LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib" > $1/env.conf
    chmod 644 $1/env.conf

}

function create_flash_d()
{
    echo "LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib" > $1/env.conf
    chmod 644 $1/env.conf

}
function create_helper_d()
{
    echo "LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:/usr/local/lib" > $1/env.conf
    chmod 644 $1/env.conf

}

function create_rule()
{
    echo "# do not edit this file, it will be overwritten on update
ACTION!=\"add|change|move|bind\", GOTO=\"mm_rolling_linux_apps_port_types_end\"
SUBSYSTEMS==\"pci\", SUBSYSTEM==\"wwan\", ATTRS{vendor}==\"0x14c3\", GOTO=\"mm_rw350_port_types\"
SUBSYSTEMS==\"usb\", ATTRS{bInterfaceNumber}==\"?*\", ENV{.MM_USBIFNUM}=\"\$attr{bInterfaceNumber}\", GOTO=\"mm_rw101_port_types\"
GOTO=\"mm_rolling_linux_apps_port_types_end\"

LABEL=\"mm_rw350_port_types\"
ATTRS{vendor}==\"0x14c3\", ATTRS{device}==\"0x4d75\", ATTR{type}==\"FASTBOOT\", ENV{ID_MM_PORT_IGNORE}=\"1\"
GOTO=\"mm_rolling_linux_apps_port_types_end\"

LABEL=\"mm_rw101_port_types\"
ATTRS{idVendor}==\"2cb7\", ATTRS{idProduct}==\"01a2\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_IGNORE}=\"1\"
ATTRS{idVendor}==\"2cb7\", ATTRS{idProduct}==\"01a2\", ENV{.MM_USBIFNUM}==\"03\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_IGNORE}=\"1\"
ATTRS{idVendor}==\"2cb7\", ATTRS{idProduct}==\"01a2\", ENV{.MM_USBIFNUM}==\"04\", ENV{ID_MM_PORT_IGNORE}=\"1\"
ATTRS{idVendor}==\"2cb7\", ATTRS{idProduct}==\"01a2\", ENV{.MM_USBIFNUM}==\"05\", ENV{ID_MM_PORT_IGNORE}=\"1\"

ATTRS{idVendor}==\"413c\", ATTRS{idProduct}==\"8213\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_IGNORE}=\"1\"
ATTRS{idVendor}==\"413c\", ATTRS{idProduct}==\"8215\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_IGNORE}=\"1\"

LABEL=\"mm_rolling_linux_apps_port_types_end\"
" > $1/76-mm-rolling-linux-apps-port-types.rules
    chmod 644 $1/76-mm-rolling-linux-apps-port-types.rules
}
function create_lvfs_rule()
{
    echo "# do not edit this file, it will be overwritten on update
ACTION!=\"add|change|move|bind\", GOTO=\"mm_rolling_linux_apps_port_types_end\"
SUBSYSTEMS==\"usb\", ATTRS{bInterfaceNumber}==\"?*\", ENV{.MM_USBIFNUM}=\"\$attr{bInterfaceNumber}\", GOTO=\"mm_rw101_port_types\"
GOTO=\"mm_rolling_linux_apps_port_types_end\"

LABEL=\"mm_rw101_port_types\"

ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0301\",\
RUN+=\"/bin/sh -c '/sbin/modprobe usbserial && /sbin/modprobe option && echo 33f8 0301 ff > /sys/bus/usb-serial/drivers/option1/new_id'\"

ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0302\",\
RUN+=\"/bin/sh -c '/sbin/modprobe usbserial && /sbin/modprobe option && echo 33f8 0302 ff > /sys/bus/usb-serial/drivers/option1/new_id'\"

ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"01a8\",\
RUN+=\"/bin/sh -c '/sbin/modprobe usbserial && /sbin/modprobe option && echo 33f8 01a8 ff > /sys/bus/usb-serial/drivers/option1/new_id'\"

ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"01a9\",\
RUN+=\"/bin/sh -c '/sbin/modprobe usbserial && /sbin/modprobe option && echo 33f8 01a9 ff > /sys/bus/usb-serial/drivers/option1/new_id'\"

ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0301\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_TYPE_AT_PRIMARY}=\"1\"
ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0302\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_TYPE_AT_PRIMARY}=\"1\"
ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0301\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_FIBOCOM_FASTBOOT}=\"1\"
ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0301\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_PORT_TYPE_GPS}=\"0\"
ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"0302\", ENV{.MM_USBIFNUM}==\"02\", SUBSYSTEM==\"tty\", ENV{ID_MM_FIBOCOM_FASTBOOT}=\"1\"
ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"01a8\", ENV{.MM_USBIFNUM}==\"03\", SUBSYSTEM==\"tty\", ENV{ID_MM_FIBOCOM_FASTBOOT}=\"1\"
ATTRS{idVendor}==\"33f8\", ATTRS{idProduct}==\"01a9\", ENV{.MM_USBIFNUM}==\"03\", SUBSYSTEM==\"tty\", ENV{ID_MM_FIBOCOM_FASTBOOT}=\"1\"

LABEL=\"mm_rolling_linux_apps_port_types_end\"
" > $1/99-mm-rolling-linux-apps-port-types.rules
    chmod 755 $1/99-mm-rolling-linux-apps-port-types.rules
}


function create_and_install()
{
    mkdir -p ${DEB_SOFT_DIRS}/lib/systemd/system/

    if [ "yes" == "${BUILD_CONFIG}" ]; then
        create_config_service ${DEB_SOFT_DIRS}/lib/systemd/system/
        mkdir -p ${DEB_SOFT_DIRS}/lib/systemd/system/rolling_config.d/
        create_config_d ${DEB_SOFT_DIRS}/lib/systemd/system/rolling_config.d/
        mkdir -p ${DEB_SOFT_DIRS}/opt/rolling/rolling_config_service/
    fi
    if [ "yes" == "${BUILD_FLASH}" ]; then
        create_flash_service ${DEB_SOFT_DIRS}/lib/systemd/system/
        mkdir -p ${DEB_SOFT_DIRS}/lib/systemd/system/rolling_flash.d/
        create_flash_d ${DEB_SOFT_DIRS}/lib/systemd/system/rolling_flash.d/
        mkdir -p ${DEB_SOFT_DIRS}/opt/rolling/rolling_flash_service/
    fi
    if [ "yes" == "${BUILD_HELPER}" ]; then
        create_helper_service ${DEB_SOFT_DIRS}/lib/systemd/system/
        mkdir -p ${DEB_SOFT_DIRS}/lib/systemd/system/rolling_helper.d/
        create_helper_d ${DEB_SOFT_DIRS}/lib/systemd/system/rolling_helper.d/
        mkdir -p ${DEB_SOFT_DIRS}/opt/rolling/rolling_helper_service/
        if [ "yes" == "${BUILD_DOWN_TOOL}" ]; then
            mkdir -p ${DEB_SOFT_DIRS}/opt/rolling/rolling_helper_service/rolling_helper_tools/
            cp ${BUILD_DIR}/application/3rd/qdl/qdl ${DEB_SOFT_DIRS}/opt/rolling/rolling_helper_service/rolling_helper_tools/
        fi
    fi

    mkdir -p ${DEB_SOFT_DIRS}/opt/rolling/rolling_fw_pkg
    mkdir -p ${DEB_SOFT_DIRS}/usr/share/dbus-1/system.d/
    create_helper_conf ${DEB_SOFT_DIRS}/usr/share/dbus-1/system.d/
    mkdir -p ${DEB_SOFT_DIRS}/usr/lib/udev/rules.d/
    create_rule ${DEB_SOFT_DIRS}/usr/lib/udev/rules.d/
	create_lvfs_rule ${DEB_SOFT_DIRS}/usr/lib/udev/rules.d/
}

function create_install()
{
    # create release dir and create config files
    # create_and_install
    # copy file to release
    if [ -d "${BUILD_DIR}/release" ];then
       rm -r ${BUILD_DIR}/release
    fi
    
    # 使用固定的安装目录，不包含项目和oem信息
    DEB_SOFT_DIRS="${BUILD_DIR}/release/dpkg"
    DEB_SOFT_DIR="${DEB_SOFT_DIRS}/opt/rolling"
    
    if [ "yes" == "${BUILD_CONFIG}" ]; then
        DEB_CONFIG_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_config_service"
    fi
    if [ "yes" == "${BUILD_FLASH}" ]; then
        DEB_FLASH_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_flash_service"
    fi
    if [ "yes" == "${BUILD_HELPER}" ]; then
        DEB_HELPER_SERVICE_DIR="${DEB_SOFT_DIR}/rolling_helper_service"
    fi
    
    create_and_install
    copy_file_to_deb_directory
    
    # 使用固定的包名，不包含项目和oem信息
    build_package="rolling_linux"
    echo "build_package: ${build_package}"
}

create_install
