/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#ifndef ___WORKSPACE_BUILD_APPLICATION_ROLLING_CONFIG_SERVICE_GENERATED_ROLLING_HELPER_GDBUS_GENERATED_H__
#define ___WORKSPACE_BUILD_APPLICATION_ROLLING_CONFIG_SERVICE_GENERATED_ROLLING_HELPER_GDBUS_GENERATED_H__

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for com.rolling.helper */

#define ROLLING_GDBUS_TYPE_HELPER (rolling_gdbus_helper_get_type ())
#define ROLLING_GDBUS_HELPER(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ROLLING_GDBUS_TYPE_HELPER, RollingGdbusHelper))
#define ROLLING_GDBUS_IS_HELPER(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ROLLING_GDBUS_TYPE_HELPER))
#define ROLLING_GDBUS_HELPER_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ROLLING_GDBUS_TYPE_HELPER, RollingGdbusHelperIface))

struct _RollingGdbusHelper;
typedef struct _RollingGdbusHelper RollingGdbusHelper;
typedef struct _RollingGdbusHelperIface RollingGdbusHelperIface;

struct _RollingGdbusHelperIface
{
  GTypeInterface parent_iface;


  gboolean (*handle_get_version) (
    RollingGdbusHelper *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_version);

  gboolean (*handle_send_mesg) (
    RollingGdbusHelper *object,
    GDBusMethodInvocation *invocation,
    GVariant *arg_msgdInt);

  gboolean (*handle_set_version) (
    RollingGdbusHelper *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_version);

  void (*cellular_state) (
    RollingGdbusHelper *object,
    const gchar *arg_state);

  void (*edl_status) (
    RollingGdbusHelper *object,
    const gchar *arg_status);

  void (*fastboot_status) (
    RollingGdbusHelper *object,
    const gchar *arg_status);

  void (*roam_region) (
    RollingGdbusHelper *object,
    const gchar *arg_state);

  void (*simcard_change) (
    RollingGdbusHelper *object,
    const gchar *arg_state);

};

GType rolling_gdbus_helper_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *rolling_gdbus_helper_interface_info (void);
guint rolling_gdbus_helper_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void rolling_gdbus_helper_complete_set_version (
    RollingGdbusHelper *object,
    GDBusMethodInvocation *invocation);

void rolling_gdbus_helper_complete_get_version (
    RollingGdbusHelper *object,
    GDBusMethodInvocation *invocation,
    const gchar *version);

void rolling_gdbus_helper_complete_send_mesg (
    RollingGdbusHelper *object,
    GDBusMethodInvocation *invocation,
    GVariant *msgOut);



/* D-Bus signal emissions functions: */
void rolling_gdbus_helper_emit_cellular_state (
    RollingGdbusHelper *object,
    const gchar *arg_state);

void rolling_gdbus_helper_emit_roam_region (
    RollingGdbusHelper *object,
    const gchar *arg_state);

void rolling_gdbus_helper_emit_simcard_change (
    RollingGdbusHelper *object,
    const gchar *arg_state);

void rolling_gdbus_helper_emit_edl_status (
    RollingGdbusHelper *object,
    const gchar *arg_status);

void rolling_gdbus_helper_emit_fastboot_status (
    RollingGdbusHelper *object,
    const gchar *arg_status);



/* D-Bus method calls: */
void rolling_gdbus_helper_call_set_version (
    RollingGdbusHelper *proxy,
    const gchar *arg_version,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean rolling_gdbus_helper_call_set_version_finish (
    RollingGdbusHelper *proxy,
    GAsyncResult *res,
    GError **error);

gboolean rolling_gdbus_helper_call_set_version_sync (
    RollingGdbusHelper *proxy,
    const gchar *arg_version,
    GCancellable *cancellable,
    GError **error);

void rolling_gdbus_helper_call_get_version (
    RollingGdbusHelper *proxy,
    const gchar *arg_version,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean rolling_gdbus_helper_call_get_version_finish (
    RollingGdbusHelper *proxy,
    gchar ** out_version,
    GAsyncResult *res,
    GError **error);

gboolean rolling_gdbus_helper_call_get_version_sync (
    RollingGdbusHelper *proxy,
    const gchar *arg_version,
    gchar ** out_version,
    GCancellable *cancellable,
    GError **error);

void rolling_gdbus_helper_call_send_mesg (
    RollingGdbusHelper *proxy,
    GVariant *arg_msgdInt,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean rolling_gdbus_helper_call_send_mesg_finish (
    RollingGdbusHelper *proxy,
    GVariant ** out_msgOut,
    GAsyncResult *res,
    GError **error);

gboolean rolling_gdbus_helper_call_send_mesg_sync (
    RollingGdbusHelper *proxy,
    GVariant *arg_msgdInt,
    GVariant ** out_msgOut,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define ROLLING_GDBUS_TYPE_HELPER_PROXY (rolling_gdbus_helper_proxy_get_type ())
#define ROLLING_GDBUS_HELPER_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ROLLING_GDBUS_TYPE_HELPER_PROXY, RollingGdbusHelperProxy))
#define ROLLING_GDBUS_HELPER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ROLLING_GDBUS_TYPE_HELPER_PROXY, RollingGdbusHelperProxyClass))
#define ROLLING_GDBUS_HELPER_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ROLLING_GDBUS_TYPE_HELPER_PROXY, RollingGdbusHelperProxyClass))
#define ROLLING_GDBUS_IS_HELPER_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ROLLING_GDBUS_TYPE_HELPER_PROXY))
#define ROLLING_GDBUS_IS_HELPER_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ROLLING_GDBUS_TYPE_HELPER_PROXY))

typedef struct _RollingGdbusHelperProxy RollingGdbusHelperProxy;
typedef struct _RollingGdbusHelperProxyClass RollingGdbusHelperProxyClass;
typedef struct _RollingGdbusHelperProxyPrivate RollingGdbusHelperProxyPrivate;

struct _RollingGdbusHelperProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  RollingGdbusHelperProxyPrivate *priv;
};

struct _RollingGdbusHelperProxyClass
{
  GDBusProxyClass parent_class;
};

GType rolling_gdbus_helper_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (RollingGdbusHelperProxy, g_object_unref)
#endif

void rolling_gdbus_helper_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
RollingGdbusHelper *rolling_gdbus_helper_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
RollingGdbusHelper *rolling_gdbus_helper_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void rolling_gdbus_helper_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
RollingGdbusHelper *rolling_gdbus_helper_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
RollingGdbusHelper *rolling_gdbus_helper_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define ROLLING_GDBUS_TYPE_HELPER_SKELETON (rolling_gdbus_helper_skeleton_get_type ())
#define ROLLING_GDBUS_HELPER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ROLLING_GDBUS_TYPE_HELPER_SKELETON, RollingGdbusHelperSkeleton))
#define ROLLING_GDBUS_HELPER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ROLLING_GDBUS_TYPE_HELPER_SKELETON, RollingGdbusHelperSkeletonClass))
#define ROLLING_GDBUS_HELPER_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ROLLING_GDBUS_TYPE_HELPER_SKELETON, RollingGdbusHelperSkeletonClass))
#define ROLLING_GDBUS_IS_HELPER_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ROLLING_GDBUS_TYPE_HELPER_SKELETON))
#define ROLLING_GDBUS_IS_HELPER_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ROLLING_GDBUS_TYPE_HELPER_SKELETON))

typedef struct _RollingGdbusHelperSkeleton RollingGdbusHelperSkeleton;
typedef struct _RollingGdbusHelperSkeletonClass RollingGdbusHelperSkeletonClass;
typedef struct _RollingGdbusHelperSkeletonPrivate RollingGdbusHelperSkeletonPrivate;

struct _RollingGdbusHelperSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  RollingGdbusHelperSkeletonPrivate *priv;
};

struct _RollingGdbusHelperSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType rolling_gdbus_helper_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (RollingGdbusHelperSkeleton, g_object_unref)
#endif

RollingGdbusHelper *rolling_gdbus_helper_skeleton_new (void);


G_END_DECLS

#endif /* ___WORKSPACE_BUILD_APPLICATION_ROLLING_CONFIG_SERVICE_GENERATED_ROLLING_HELPER_GDBUS_GENERATED_H__ */
