#!/bin/bash
#remove vid:pid link file befor packge remove
# rm -rf /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/*:*
systemctl daemon-reload

if [ -d "/usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d" ]; then
    if [ -d "/opt/rolling/rolling_ma_service" ]; then
        rm -rf /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d
    fi
elif [ -d "/usr/lib64/ModemManager/fcc-unlock.d" ]; then
    if [ -d "/opt/rolling/rolling_ma_service" ]; then
        rm -rf /usr/lib64/ModemManager/fcc-unlock.d
    fi
fi

if [ -d "/etc/opt/rolling/config_file/rolling_config_service/" ]; then
    rm -rf /etc/opt/rolling/config_file/rolling_config_service/
fi

if [ -d "/etc/opt/rolling/config_file/rolling_flash_service/" ]; then
    rm -rf /etc/opt/rolling/config_file/rolling_flash_service/
fi
rm -rf /etc/opt/rolling/config_file/

if [ -d "/etc/opt/rolling/run" ]; then
    rm -rf /etc/opt/rolling/run
fi

if [ ! -d "/etc/opt/rolling/rolling_fw_pkg/rolling_config_file" ]; then
    rm -rf /etc/opt/rolling/rolling_fw_pkg/
    rm -rf /etc/opt/rolling/
fi